# Simulated daily request to your render project so that the service doesn't go down
name: Continuos render ping

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  curl-website:
    runs-on: ubuntu-latest

    steps:
    - name: Send GET request to Render service
      run: curl -s "https://my-strapi-project-abjk.onrender.com"
